import type { TaskRecord } from '../types/task';

const now = new Date();
const ago = (minutes: number) => new Date(now.getTime() - minutes * 60 * 1000).toISOString();

export const DEMO_TASKS: TaskRecord[] = [
  {
    taskId: 'TASK-101',
    title: 'Add JWT refresh token support to auth service',
    description: 'Implement sliding session with refresh tokens',
    project: 'rivus-core',
    targetAgent: 'claude',
    priority: 1,
    status: '执行中',
    workspacePath: '/Users/dev/rivus-core',
    logPath: '/tmp/task-101.log',
    progressSummary: 'Implemented token rotation logic. Working on the revocation list. Tests pending.',
    claimedBy: 'claude@anthropic',
    claimedAt: ago(42),
    updatedAt: ago(2),
    lastHeartbeatAt: ago(1),
    runnerKind: 'execute',
    runnerRound: 2,
    runnerAgent: 'claude',
    runId: 'run-abc123',
  },
  {
    taskId: 'TASK-103',
    title: 'Migrate logging pipeline to structured JSON format',
    description: 'Replace plaintext logs with structured JSON across all services',
    project: 'infra',
    targetAgent: 'codex',
    priority: 2,
    status: '修复中',
    workspacePath: '/Users/dev/infra',
    progressSummary: 'Reviewer flagged timestamp format inconsistency. Fixing now.',
    claimedBy: 'codex@openai',
    claimedAt: ago(120),
    updatedAt: ago(5),
    lastHeartbeatAt: ago(3),
    runnerKind: 'execute',
    runnerRound: 3,
    runnerAgent: 'codex',
  },
  {
    taskId: 'TASK-105',
    title: 'Add dark mode support to dashboard',
    description: 'Implement CSS variable-based theming with system preference detection',
    project: 'rivus-web',
    targetAgent: 'claude',
    priority: 2,
    status: '待复核',
    workspacePath: '/Users/dev/rivus-web',
    progressSummary: 'Dark mode implemented using CSS variables. All components updated. PR created.',
    prLink: 'https://github.com/example/rivus-web/pull/42',
    claimedBy: 'claude@anthropic',
    claimedAt: ago(200),
    updatedAt: ago(15),
    reviewRound: 1,
    executionSessionId: 'sess-xyz',
    executionSessionName: 'dark-mode-impl',
  },
  {
    taskId: 'TASK-108',
    title: 'Set up E2E test pipeline with Playwright',
    description: 'Configure Playwright for cross-browser E2E tests in CI',
    project: 'rivus-web',
    targetAgent: 'codex',
    priority: 3,
    status: '待处理',
    updatedAt: ago(60),
    createdAt: ago(300),
  },
  {
    taskId: 'TASK-109',
    title: 'Optimize database query performance for task listing',
    description: 'Add indexes and optimize N+1 queries in task list endpoint',
    project: 'rivus-core',
    targetAgent: 'claude',
    priority: 3,
    status: '待处理',
    updatedAt: ago(90),
    createdAt: ago(400),
  },
  {
    taskId: 'TASK-096',
    title: 'Refactor agent discovery to support plugin architecture',
    description: 'Extract agent discovery into pluggable provider pattern',
    project: 'agent-finder',
    targetAgent: 'claude',
    priority: 1,
    status: '待验收',
    progressSummary: 'Plugin architecture implemented. All existing providers migrated.',
    resultSummary: 'Refactored agent discovery into provider pattern. 4 providers migrated. Tests passing.',
    prLink: 'https://github.com/example/agent-task-loop/pull/28',
    claimedAt: ago(500),
    updatedAt: ago(180),
    publishBranch: 'feat/plugin-discovery',
    publishCommit: 'a3f9c12',
    publishedAt: ago(180),
  },
  {
    taskId: 'TASK-089',
    title: 'Fix race condition in concurrent task claim',
    description: 'Two agents can claim the same task simultaneously',
    project: 'rivus-core',
    targetAgent: 'codex',
    priority: 1,
    status: '已完成',
    resultSummary: 'Added optimistic locking with version field. Race condition eliminated.',
    prLink: 'https://github.com/example/rivus-core/pull/55',
    updatedAt: ago(720),
    publishedAt: ago(700),
  },
  {
    taskId: 'TASK-092',
    title: 'Implement rate limiting for external API calls',
    description: 'Add token bucket rate limiter for Feishu and GitHub API clients',
    project: 'rivus-core',
    targetAgent: 'coco',
    priority: 2,
    status: '已失败',
    progressSummary: 'Attempted token bucket implementation but hit circular dependency issue.',
    lastError: 'Circular dependency detected between RateLimiter and HttpClient modules. Needs architectural review before retry.',
    updatedAt: ago(480),
    claimedAt: ago(600),
  },
];
