import type { TaskRecord } from '../types/task';
import { createFakeSessionProvider, type SessionProvider } from './data/session-provider';

/**
 * Fixture tasks spanning every TaskStatus plus the session fields the preview
 * pane reads, so `tui --demo` exercises the whole dashboard without a backend.
 * Timestamps are anchored to an injected `now` so the demo looks "live".
 */
export function demoTasks(now: number): TaskRecord[] {
  const ago = (minutes: number) => new Date(now - minutes * 60_000).toISOString();
  const secAgo = (seconds: number) => new Date(now - seconds * 1000).toISOString();
  const history = (lines: string[]) => lines.join('\n');

  return [
    {
      taskId: 'TASK-101',
      title: 'Wire task provider boundary into runtime',
      description: 'Adopt the new provider abstraction in the loop runtime',
      project: 'agent-task-loop',
      targetAgent: 'claude',
      priority: 3,
      status: '执行中',
      workspacePath: '/Users/dev/agent-task-loop',
      logPath: '/tmp/task-101.log',
      progressSummary: 'Implemented provider wiring. Running the vitest suite now.',
      claimedBy: 'claude@anthropic',
      claimedAt: ago(42),
      updatedAt: secAgo(8),
      lastHeartbeatAt: secAgo(4),
      runnerKind: 'execute',
      runnerRound: 2,
      runnerAgent: 'claude',
      runnerPid: 41822,
      runId: 'run-abc123',
      executionSessionId: 'sess-101-exec',
      executionSessionName: 'execution-claude-r2',
      sessionHistory: history([
        `[${ago(40)}] | round=1 | kind=execute | agent=claude | name=execution-claude-r1 | id=sess-101-r1`,
        `[${ago(14)}] | round=2 | kind=execute | agent=claude | name=execution-claude-r2 | id=sess-101-exec`,
      ]),
    },
    {
      taskId: 'TASK-102',
      title: '修复并发认领的竞态条件',
      description: 'Two agents can claim the same task simultaneously',
      project: 'rivus-core',
      targetAgent: 'codex',
      priority: 2,
      status: '修复中',
      workspacePath: '/Users/dev/rivus-core',
      logPath: '/tmp/task-102.log',
      progressSummary: 'Reviewer flagged a timestamp inconsistency. Applying the fix.',
      claimedBy: 'codex@openai',
      claimedAt: ago(120),
      updatedAt: secAgo(20),
      lastHeartbeatAt: secAgo(30),
      runnerKind: 'execute',
      runnerRound: 3,
      runnerAgent: 'codex',
      runnerPid: 51200,
      sessionHistory: history([
        `[${ago(118)}] | round=1 | kind=execute | agent=codex | name=exec-r1`,
        `[${ago(30)}] | round=2 | kind=review | agent=claude | name=review-r2`,
        `[${ago(5)}] | round=3 | kind=execute | agent=codex | name=exec-r3`,
      ]),
    },
    {
      taskId: 'TASK-103',
      title: 'Add agent session preview pane to the TUI',
      description: 'Show live session output for the selected task',
      project: 'agent-task-loop',
      targetAgent: 'claude',
      priority: 1,
      status: '进行中',
      updatedAt: ago(3),
      createdAt: ago(50),
      currentOwner: 'pan',
    },
    {
      taskId: 'TASK-104',
      title: 'Migrate logging pipeline to structured JSON',
      description: 'Replace plaintext logs with structured JSON',
      project: 'infra',
      targetAgent: 'glm',
      priority: 2,
      status: '待复核',
      workspacePath: '/Users/dev/infra',
      logPath: '/tmp/task-104.log',
      reviewLogPath: '/tmp/task-104-review.log',
      progressSummary: 'Structured logging implemented across all services. PR opened.',
      prLink: 'https://github.com/example/infra/pull/77',
      updatedAt: ago(12),
      reviewRound: 1,
      runnerKind: 'review',
      runnerAgent: 'claude',
      runnerRound: 1,
      lastHeartbeatAt: secAgo(75),
      executionSessionId: 'sess-104-exec',
      reviewSessionId: 'sess-104-review',
      reviewSessionName: 'review-claude-r1',
      sessionHistory: history([
        `[${ago(60)}] | round=1 | kind=execute | agent=glm | name=exec-r1 | id=sess-104-exec`,
        `[${ago(12)}] | round=1 | kind=review | agent=claude | name=review-claude-r1 | id=sess-104-review`,
      ]),
    },
    {
      taskId: 'TASK-105',
      title: 'Decide rollout strategy for provider migration',
      description: 'Needs a human decision on phased vs big-bang rollout',
      project: 'agent-task-loop',
      targetAgent: 'claude',
      priority: 1,
      status: '待决策',
      progressSummary: 'Two options drafted; awaiting a maintainer decision.',
      updatedAt: ago(25),
      currentOwner: 'pan',
    },
    {
      taskId: 'TASK-106',
      title: 'Set up E2E pipeline with Playwright',
      description: 'Cross-browser E2E tests in CI',
      project: 'rivus-web',
      targetAgent: 'codex',
      priority: 3,
      status: '待处理',
      updatedAt: ago(70),
      createdAt: ago(300),
    },
    {
      taskId: 'TASK-107',
      title: 'Publish provider abstraction to npm',
      description: 'Ready to publish once approved',
      project: 'agent-task-loop',
      targetAgent: 'claude',
      priority: 2,
      status: '待发布',
      resultSummary: 'Provider abstraction complete; awaiting publish.',
      prLink: 'https://github.com/example/agent-task-loop/pull/29',
      updatedAt: ago(35),
      publishBranch: 'feat/provider-boundary',
    },
    {
      taskId: 'TASK-108',
      title: 'Refactor agent discovery to plugin architecture',
      description: 'Extract discovery into a pluggable provider pattern',
      project: 'agent-finder',
      targetAgent: 'claude',
      priority: 1,
      status: '待验收',
      progressSummary: 'Plugin architecture implemented; awaiting acceptance.',
      resultSummary: 'Refactored discovery into a provider pattern. 4 providers migrated.',
      prLink: 'https://github.com/example/agent-finder/pull/28',
      updatedAt: ago(180),
      currentOwner: 'pan',
    },
    {
      taskId: 'TASK-109',
      title: 'Fix flaky token-refresh test',
      description: 'Intermittent failure under load',
      project: 'rivus-core',
      targetAgent: 'codex',
      priority: 1,
      status: '已完成',
      resultSummary: 'Stabilized with deterministic clock injection.',
      prLink: 'https://github.com/example/rivus-core/pull/55',
      updatedAt: ago(720),
      publishedAt: ago(700),
    },
    {
      taskId: 'TASK-110',
      title: 'Implement rate limiting for external APIs',
      description: 'Token bucket limiter for Feishu and GitHub clients',
      project: 'rivus-core',
      targetAgent: 'coco',
      priority: 2,
      status: '已失败',
      progressSummary: 'Attempted token bucket but hit a circular dependency.',
      lastError:
        'Circular dependency between RateLimiter and HttpClient. Needs an architectural review before retry.',
      updatedAt: ago(480),
      claimedAt: ago(600),
    },
  ];
}

/** Synthetic session provider for `--demo`: gives live tasks a fake log tail. */
export function demoSessionProvider(): SessionProvider {
  const logTail = [
    '12:00:01 running vitest…',
    '12:00:03 tests/tui/logic/sort.test.ts ✓',
    '12:00:04 tests/tui/logic/filter.test.ts ✓',
    '12:00:05 12 passed',
  ];
  return createFakeSessionProvider({
    'TASK-101': { logTail, hasLog: true },
    'TASK-102': { logTail: ['12:01:10 applying fix…', '12:01:12 lint clean'], hasLog: true },
    'TASK-104': { logTail: ['12:02:00 reviewing diff…', '12:02:09 2 findings'], hasLog: true },
  });
}
